"""
patchwork.tools.sandbox
========================
Deterministic, sandboxed pytest execution for the Patchwork self-healing
code-audit engine.

This module is intentionally LLM-agnostic: it knows nothing about Ollama,
LangGraph, or Qwen. Its only job is to take a source module and a test
suite (both as strings), execute the tests in an isolated temporary
directory via `pytest`, and return a strictly-typed, truncated result.

Design goals (see `critical_engineering_and_execution_advice`):
    * Every subprocess call is time-boxed. A hallucinated `while True:`
      in generated test code must never hang the agent process.
    * Generated code/tests are never written into the project directory.
      Every run gets a disposable `tempfile.TemporaryDirectory()`.
    * Tool output is truncated before it re-enters the LLM context window,
      to protect the ~1.5 GB VRAM KV-cache budget on a 4 GB GPU.
    * Structured logging only -- no `print()`. This module logs via the
      standard `logging` module with structured `extra` fields; JSON
      formatting is configured by the application entrypoint, keeping
      telemetry concerns decoupled from this tool's core logic.
"""

from __future__ import annotations

import logging
import platform
import subprocess
import sys
import tempfile
import time
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Final

from pydantic import BaseModel, Field

logger = logging.getLogger("patchwork.tools.sandbox")

# --- Tunables -------------------------------------------------------------

DEFAULT_TIMEOUT_SEC: Final[int] = 10
MAX_OUTPUT_CHARS: Final[int] = 1000
MAX_OUTPUT_LINES: Final[int] = 20
MAX_MEMORY_MB: Final[int] = 512

_SOURCE_MODULE_NAME: Final[str] = "module_under_test"
_TEST_MODULE_NAME: Final[str] = "test_module_under_test"


class SandboxExecutionResult(BaseModel):
    """Strictly-typed result of a single sandboxed pytest run.

    Attributes:
        passed: True only if pytest exited with code 0 and did not time out.
        returncode: Raw pytest exit code, or None if the process never
            returned one (e.g. it timed out or failed to launch).
        timed_out: True if the subprocess was killed for exceeding
            `timeout_sec`.
        stdout: Truncated, tail-anchored stdout from pytest.
        stderr: Truncated, tail-anchored stderr from pytest.
        duration_sec: Wall-clock time the subprocess actually ran for.
        error_message: Populated only for infrastructure-level failures
            (e.g. pytest executable not found), never for normal test
            failures -- those are represented via `passed=False` plus the
            captured stdout/stderr instead.
    """

    passed: bool
    returncode: int | None = None
    timed_out: bool = False
    stdout: str = ""
    stderr: str = ""
    duration_sec: float = Field(ge=0.0)
    error_message: str | None = None


def _truncate_tail(
    text: str,
    max_chars: int = MAX_OUTPUT_CHARS,
    max_lines: int = MAX_OUTPUT_LINES,
) -> str:
    """Truncates text to its last N lines and last N characters.

    Keeps the *tail* of the output, since pytest tracebacks and assertion
    failures are almost always at the end of stdout/stderr. This is what
    protects the SLM's context window from a 500-line traceback blowing
    the KV cache on constrained VRAM.

    Args:
        text: Raw text to truncate.
        max_chars: Maximum characters to retain from the end of `text`.
        max_lines: Maximum lines to retain from the end of `text`.

    Returns:
        The truncated text, prefixed with a marker if truncation occurred.
    """
    if not text:
        return text

    lines = text.splitlines()
    truncated_by_lines = len(lines) > max_lines
    if truncated_by_lines:
        lines = lines[-max_lines:]
    tail = "\n".join(lines)

    truncated_by_chars = len(tail) > max_chars
    if truncated_by_chars:
        tail = tail[-max_chars:]

    if truncated_by_lines or truncated_by_chars:
        tail = f"...[truncated]...\n{tail}"

    return tail


def _sanitize_test_imports(test_code: str) -> str:
    """Neutralizes import lines in SLM-generated tests that reference the
    source module by its original (user-supplied) name or via a relative
    import, since the sandbox always mounts the source under the fixed
    name `module_under_test`.

    Args:
        test_code: Raw pytest suite generated by the SLM.

    Returns:
        The test code with offending import lines commented out. This is
        a best-effort line-level heuristic, not a parser -- the sandbox
        re-injects a single canonical `from module_under_test import *`
        ahead of the test code to supply the real names.
    """
    sanitized_lines = []
    for line in test_code.splitlines():
        stripped = line.strip()
        looks_like_source_import = stripped.startswith(
            ("from .", f"from {_SOURCE_MODULE_NAME}", f"import {_SOURCE_MODULE_NAME}")
        )
        if looks_like_source_import:
            sanitized_lines.append(f"# [patchwork:stripped] {line}")
        else:
            sanitized_lines.append(line)
    return "\n".join(sanitized_lines)


def _limit_subprocess_memory() -> None:
    """`preexec_fn` target that caps the pytest subprocess's virtual
    address space to `MAX_MEMORY_MB`.

    POSIX-only, best-effort guard against generated test code that
    allocates unbounded arrays and OOMs the host machine before the
    `timeout_sec` wall-clock limit even has a chance to fire. This is a
    no-op on Windows, where the `resource` module is unavailable.

    Note:
        `preexec_fn` runs in the forked child between `fork()` and
        `exec()`; keeping it to a single `setrlimit` call (no other
        Python machinery) avoids the well-known fork/thread hazards.
    """
    import resource  # POSIX-only; imported lazily so Windows never touches it.

    limit_bytes = MAX_MEMORY_MB * 1024 * 1024
    # mypy on Windows has no `resource` stub at all (module doesn't exist
    # there) -- this function is only ever called on POSIX, guarded by
    # platform.system() at the call site, but mypy checks function bodies
    # statically regardless of that runtime guard. Safe to ignore here.
    resource.setrlimit(resource.RLIMIT_AS, (limit_bytes, limit_bytes))  # type: ignore[attr-defined, unused-ignore]


@contextmanager
def tempfile_dir() -> Iterator[Path]:
    """Context manager yielding a disposable temporary directory as a
    `pathlib.Path` instead of the raw `str` `tempfile` returns natively.

    Isolated into its own function purely so `run_pytest_sandbox` reads
    cleanly; kept in this module rather than a shared utility module for
    now since it has exactly one caller.

    Yields:
        The temporary directory path. The directory and all its contents
        are purged on exit, even if the caller raises.
    """
    with tempfile.TemporaryDirectory(prefix="patchwork_sandbox_") as tmpdir:
        yield Path(tmpdir)


def run_pytest_sandbox(
    source_code: str,
    test_code: str,
    timeout_sec: int = DEFAULT_TIMEOUT_SEC,
) -> SandboxExecutionResult:
    """Executes a generated pytest suite against generated source code in
    an isolated, disposable temporary directory.

    Args:
        source_code: The full contents of the module under test.
        test_code: The full contents of the pytest suite to run against it.
        timeout_sec: Hard wall-clock limit, in seconds, for the pytest
            subprocess. Must be strictly positive.

    Returns:
        A `SandboxExecutionResult` describing the outcome. This function
        never raises for normal test failures or timeouts -- those are
        represented as `passed=False` / `timed_out=True` respectively. It
        only raises `ValueError` for invalid arguments.

    Raises:
        ValueError: If `timeout_sec` is not a positive number.
    """
    if timeout_sec <= 0:
        raise ValueError(f"timeout_sec must be positive, got {timeout_sec!r}")

    start_time = time.perf_counter()

    with tempfile_dir() as tmp_path:
        source_path = tmp_path / f"{_SOURCE_MODULE_NAME}.py"
        test_path = tmp_path / f"{_TEST_MODULE_NAME}.py"

        sanitized_test_code = _sanitize_test_imports(test_code)
        full_test_content = (
            "import sys\n"
            f"sys.path.insert(0, {str(tmp_path)!r})\n"
            f"from {_SOURCE_MODULE_NAME} import *  # noqa: F401,F403\n\n"
            f"{sanitized_test_code}\n"
        )

        try:
            source_path.write_text(source_code, encoding="utf-8")
            test_path.write_text(full_test_content, encoding="utf-8")
        except OSError as exc:
            duration = time.perf_counter() - start_time
            logger.error(
                "sandbox_write_failed",
                extra={"event": "sandbox_write_failed", "error": str(exc)},
            )
            return SandboxExecutionResult(
                passed=False,
                duration_sec=duration,
                error_message=f"Failed to write sandbox files: {exc}",
            )

        preexec = _limit_subprocess_memory if platform.system() != "Windows" else None

        try:
            proc = subprocess.run(
                [sys.executable, "-m", "pytest", "-v", str(test_path)],
                capture_output=True,
                text=True,
                timeout=timeout_sec,
                cwd=str(tmp_path),
                preexec_fn=preexec,
                check=False,  # non-zero exit (test failures) is an expected outcome, not an error
            )
            duration = time.perf_counter() - start_time
            passed = proc.returncode == 0
            logger.info(
                "sandbox_run_complete",
                extra={
                    "event": "sandbox_run_complete",
                    "passed": passed,
                    "returncode": proc.returncode,
                    "duration_sec": round(duration, 3),
                },
            )
            return SandboxExecutionResult(
                passed=passed,
                returncode=proc.returncode,
                timed_out=False,
                stdout=_truncate_tail(proc.stdout),
                stderr=_truncate_tail(proc.stderr),
                duration_sec=duration,
            )

        except subprocess.TimeoutExpired as exc:
            duration = time.perf_counter() - start_time
            logger.warning(
                "sandbox_run_timeout",
                extra={"event": "sandbox_run_timeout", "timeout_sec": timeout_sec},
            )
            raw_stdout = exc.stdout
            raw_stderr = exc.stderr
            partial_stdout = (
                raw_stdout.decode("utf-8", errors="replace")
                if isinstance(raw_stdout, bytes)
                else (raw_stdout or "")
            )
            partial_stderr = (
                raw_stderr.decode("utf-8", errors="replace")
                if isinstance(raw_stderr, bytes)
                else (raw_stderr or "")
            )
            return SandboxExecutionResult(
                passed=False,
                timed_out=True,
                stdout=_truncate_tail(partial_stdout),
                stderr=_truncate_tail(partial_stderr),
                duration_sec=duration,
                error_message=f"Execution exceeded {timeout_sec}s timeout.",
            )

        except FileNotFoundError as exc:
            duration = time.perf_counter() - start_time
            logger.error(
                "sandbox_pytest_not_found",
                extra={"event": "sandbox_pytest_not_found", "error": str(exc)},
            )
            return SandboxExecutionResult(
                passed=False,
                duration_sec=duration,
                error_message=f"pytest executable not found: {exc}",
            )
